server:
  port: 8080

database:
  url: "localhost:5432/postgres?sslmode=disable&search_path=autojong"
  user: postgres
  password: postgres
  pool_size: 20

migration:
  directory: "migrations"

jwt_auth:
  key: "MyVerySecretKeyForJWTTokenRealizationForArchitectorAuthAppMyVerySecretKeyForJWTTokenRealizationForArchitectorAuthApp"

